### ISSUE TITLE
Would you please give "Array. Consolidate" more examples？

### ISSUE THREAD

**Issue by suyuan** [TileDB-Inc/TileDB-Java#163]
I found in the testing process so many fragments, each update will have new fragments to create, I implemented according to the specifications for the Array. Consolidate, fragments did not decrease, which increases. So if there are any more examples of array.consonlidate, it's best to visually see the fragment reduction

**Comment by gsvic** [comment]
Hi @suyuan.

We just released a new TileDB-Java version that includes the vacuum method for cleaning up fragments. You can take a look at the docs through this link: https://docs.tiledb.com/main/api-usage/consolidating-arrays#post-consolidation-vacuuming

Release Link: https://github.com/TileDB-Inc/TileDB-Java/releases/tag/0.2.7

Furthermore, you can take a look at the following examples to see how you can use vacuum in TileDB-Java:

- Unit Test: https://github.com/TileDB-Inc/TileDB-Java/blob/release-0.2.7/src/test/java/io/tiledb/java/api/FragmentsConsolidationTest.java#L53
- Example: https://github.com/TileDB-Inc/TileDB-Java/blob/release-0.2.7/src/main/java/examples/io/tiledb/java/api/ArrayConsolidateExample.java

Let us know for further questions.  +@Shelnutt2

**Comment by ihnorton** [comment]
Please leave a comment or reopen if further clarification needed. Thanks!
