### ISSUE TITLE
Split spark work into it's own repo

### ISSUE THREAD

**Issue by jakebolewski** [TileDB-Inc/TileDB-Java#18]

**Comment by jakebolewski** [comment]
https://github.com/TileDB-Inc/TileDB-Spark

**Comment by jakebolewski** [comment]
Until #23 is closed, it will be difficult to transition the spark interface to it's own repo.  Instead we should remove the spark source code and build extensions from the master branch and it should solely live on it's own branch.

cc @npapa

**Comment by npapa** [comment]
https://github.com/TileDB-Inc/TileDB-Java/pull/28
