### ISSUE TITLE
Embed native .so inside the JAR

### ISSUE THREAD

**Issue by tdenniston** [TileDB-Inc/TileDB-Java#69]
The native `.so` component of TileDB-Java is currently not shipped as a part of the .jar. This means when using TileDB-Java one has to manually set `-Djava.library.path` to the location of the native library. We should embed the native libraries in the .jar.

**Comment by jakebolewski** [comment]
Typically this is done by having a jar only for the native lib and then doing runtime dlloading for the correct platform.  TileDB-Java would then depend on this libtiledb.jar.  This is a big project unfortunately, but if we limit the number of platforms initially it shouldn't be too difficult.
