### ISSUE TITLE
getItem takes Integer but OffsetBuffer stores BigInteger

### ISSUE THREAD

**Issue by Shelnutt2** [TileDB-Inc/TileDB-Java#70]
The `NativeArray.getItem(int index)` takes Integer but for variable length attributes the offset is stored as a uint64_t which is a BigInteger. This means is possible to have an offset that is bigger than can be selected. Should getItem take a BigInteger instead of a int primative?

**Comment by jakebolewski** [comment]
We can have an overload for this (as well as long), the issue is that BigInteger is really slow as it has to be heap allocated.  We should probably also have an API that returns long's for Varlen attributes.

**Comment by ihnorton** [comment]
ch8569
