### ISSUE TITLE
uint64_tArray takes/returns BigInteger's instead of Long

### ISSUE THREAD

**Issue by Shelnutt2** [TileDB-Inc/TileDB-Java#85]
https://github.com/TileDB-Inc/TileDB-Java/blob/master/src/main/java/io/tiledb/libtiledb/uint64_tArray.java#L42

It looks like in the removal of BigInteger and having uint64_t return longs the `getItem`/`setItem` methods on `uint64_tArray` still use BigInteger

**Comment by jakebolewski** [comment]
This is an autogenerated class from SWIG so there is not much we can do to change the behavior.
